# Generated by Django 4.2.6 on 2023-11-04 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='Online', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teamphoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(blank=True, upload_to='imagesz')),
                ('staff_possition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.position')),
            ],
        ),
    ]
