# Generated by Django 4.2.6 on 2023-10-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_category',
            name='service_name',
            field=models.CharField(default='Online', max_length=50),
        ),
    ]
